[package]
name = "days_12_and_on"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
rayon = "1.7.0"
serde = "1.0.163"
serde_json = "1.0.96"
